import { SafeType } from "../utils/typebox.js";
import { spotifyImageSchema } from "./guessSong.js";

export const artistSchema = SafeType.Object(
    {
        id: SafeType.Integer({
            description:
                "A numeric identifier for an artist. Generated by the backend, " +
                "unique and unchangeable.",
        }),
        musixmatchArtistId: SafeType.Integer({
            description: "Identifier for an artist given by MusixMatch",
        }),
        spotifyArtistId: SafeType.String({
            description: "Identifier for an artist given by spotify",
        }),
        artistIsrc: SafeType.String({
            description:
                "Identifier for an artist accepted by multiple platforms",
        }),
        name: SafeType.String({
            description: "Name of the artist, does not have to be unique.",
        }),
        imageUrls: SafeType.Optional(
            SafeType.String({
                description:
                    "Url to download the artist's portrait image, if available.",
            })
        ),
        images: SafeType.Array(spotifyImageSchema),
        externalUrls: SafeType.Object(
            {
                spotify: SafeType.String({
                    description:
                        "Url that will allow users to be redirected to the artist's profile on Spotify.",
                }),
            },
            { additionalProperties: true }
        ),
        genres: SafeType.Array(
            SafeType.String({
                description: "Genres associated with the artist.",
            })
        ),
        followers: SafeType.Object({
            href: SafeType.Nullable(SafeType.String()),
            total: SafeType.Number({
                description: "The number of followers the artist has.",
            }),
        }),
        popularity: SafeType.Number({
            description:
                "The popularity of the artist. " +
                "The value will be between 0 and 100, with 100 being the most popular. " +
                "The artist's popularity is calculated from the popularity of all the artist's tracks.",
        }),
    },
    {
        $id: "ArtistSchema",
        title: "artistSchema",
    }
);
