import { Static } from "@sinclair/typebox";
import { SafeType } from "../utils/typebox.js";

export const artisSchema = SafeType.Object(
    {
        id: SafeType.Integer({
            description:
                "A numeric identifier for an arrtis. Generated by the backend, " +
                "unique and unchangeable.",
        }),
        musixmatchArtistId: SafeType.String({
            description:
                "Numeric identifier for an artist given by MusixMatch"
        }),
    },
    {
        $id: "ArtistSchema",
        title: "artistSchema",
    }
);

export type User = Static<typeof artisSchema>;