import { Static } from "@sinclair/typebox";
import { SafeType } from "../utils/typebox.js";

// juana!!!
export const friendSchema = SafeType.Object(
    {
        id: SafeType.Integer({
            description:
                "A numeric identifier for a user. Generated by the backend, " +
                "unique and unchangeable.",
        }),
        name: SafeType.String({
            maxLength: 25,
            minLength: 3,
            description:
                "The user's display name. It does not need to be unique.",
        }),
        score: SafeType.Integer({
            description: "Score of an user.",
        }),
        lastUpdated: SafeType.String({
            format: "date-time",
            description: "Last update of the leaderboard.",
        }),
    },
    {
        $id: "friendSchema",
        title: "friendSchema",
    }
);

const LeaderboardSchema = SafeType.Array(friendSchema);
export type LeaderboardType = Static<typeof LeaderboardSchema>
export type FriendType = Static<typeof friendSchema>
